input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    gsub => [
      "message", "password=\\S+", "password=****",
      "message", "Bearer \\S+", "Bearer ****",
      "message", "token=\\S+", "token=****"
    ]
  }

  if [level] == "ERROR" {
    mutate { add_tag => ["error"] }
  }

  if [message] =~ /(?i)(login|logout|401|403)/ {
    mutate { add_tag => ["security"] }
  }

  if [message] =~ /(?i)(order|stock|warehouse)/ {
    mutate { add_tag => ["business"] }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "smartsupply-logs-%{+YYYY-MM-dd}"
  }

  stdout { codec => rubydebug }
}